### ISSUE TITLE
Merge forces with dradtke 

### ISSUE THREAD

**Issue by displague** [armorfret/packer-builder-linode#1]
This PR https://github.com/dradtke/packer-builder-linode/pull/4 (@dradtke) represents a working Linode Packer builder, based on Linode APIv4.  There are a few bugs to work out, namely images that are too large don't get detected until after the image is processed (@akerl addressed this problem in the Terraform `linode_image` resource).

I'd like to get packer-builder-linode support upstreamed into packer proper.  Knowing that this repo exists means we have more resources to pool towards a common goal.

The advice I was given from Hashicorp's team was to folllow the examples (practices) of the GCP builder.

**Comment by akerl** [comment]
Agreed; new updates there look awesome. Gonna nuke this repo and replace w/ a fork of that so I can more easily collaborate 😄
